# Use a imagem base opengatecollaboration/gate
FROM opengatecollaboration/gate:9.4-docker


# Atualize os repositórios e instale o Python3 e pip
RUN yum update -y && \
    yum install -y python3 python3-pip && \
    yum clean all

# Instale as bibliotecas Python a partir do requirements.txt
COPY requirements.txt /tmp/requirements.txt
RUN pip3 install --upgrade pip && \
    pip3 install -r /tmp/requirements.txt

 

# Copie o script de entrada personalizado para o contêiner
COPY run.sh /run.sh

# Torne o script de entrada executável
RUN chmod +x /run.sh

# Mantenha o script original runGate.sh (já presente na imagem base)
 

# Defina o entrypoint para usar o script personalizado
ENTRYPOINT ["/run.sh"]

 



# Defina o comando padrão como nada, permitindo sobrescrever via docker-compose ou comandos
CMD []
