
# Digitizer for Indium-111
# Primary window: 20% centered around 171 keV and 245 keV
# Secondary window: 10% centered around 209 keV

# Adder
/gate/digitizer/Singles/insert adder

# Readout
/gate/digitizer/Singles/insert readout
#/gate/digitizer/Singles/readout/setPolicy TakeEnergyCentroid
/gate/digitizer/Singles/readout/setDepth 1


# Intrinsic Spatial Blurring
/gate/digitizer/Singles/insert spblurring
/gate/digitizer/Singles/spblurring/setSpresolution 3.97 mm
/gate/digitizer/Singles/spblurring/verbose 0

# Energy Blurring
/gate/digitizer/Singles/insert blurring
/gate/digitizer/Singles/blurring/setLaw linear
/gate/digitizer/Singles/blurring/linear/setResolution 0.1
/gate/digitizer/Singles/blurring/linear/setEnergyOfReference 171.0 keV
/gate/digitizer/Singles/blurring/linear/setSlope -0.0194 1/MeV

# Thresholds In111
/gate/digitizer/Singles/insert thresholder
/gate/digitizer/Singles/thresholder/setThreshold 3. keV
/gate/digitizer/Singles/insert upholder
/gate/digitizer/Singles/upholder/setUphold 400. keV

# Scatter Windows
/gate/digitizer/name scatter
/gate/digitizer/insert singleChain
/gate/digitizer/scatter/setInputName Singles
/gate/digitizer/scatter/insert thresholder
/gate/digitizer/scatter/thresholder/setThreshold 198.55 keV
/gate/digitizer/scatter/insert upholder
/gate/digitizer/scatter/upholder/setUphold 219.45 keV

# In-111 : 171 keV windows, width of 20%
/gate/digitizer/name peak171
/gate/digitizer/insert singleChain
/gate/digitizer/peak171/setInputName Singles
/gate/digitizer/peak171/insert thresholder
/gate/digitizer/peak171/thresholder/setThreshold 153.9 keV
/gate/digitizer/peak171/insert upholder
/gate/digitizer/peak171/upholder/setUphold 188.1 keV


# In-111 : 245 keV windows, width of 20%
/gate/digitizer/name peak245
/gate/digitizer/insert singleChain
/gate/digitizer/peak245/setInputName Singles
/gate/digitizer/peak245/insert thresholder
/gate/digitizer/peak245/thresholder/setThreshold 220.5 keV
/gate/digitizer/peak245/insert upholder
/gate/digitizer/peak245/upholder/setUphold 269.5 keV


# Dead time -> no dead time simulated here
/gate/digitizer/Singles/insert deadtime
/gate/digitizer/Singles/deadtime/setDeadTime 1650 ns
/gate/digitizer/Singles/deadtime/setMode paralysable
/gate/digitizer/Singles/deadtime/chooseDTVolume crystal_volume

