
# -------------------
# GE Discovery NM 670
# -------------------

# Default orientation is collimator look towards Z axis (photon going towards collimator are -Z)
# Rotation around X to start looking towards Y, like CT image.

# SPECT Head: main volume, everything is included in SPECThead
# the name MUST be SPECThead
/gate/world/daughters/name SPECThead
/gate/world/daughters/insert box
/gate/SPECThead/geometry/setXLength 57.6 cm
/gate/SPECThead/geometry/setYLength 44.6 cm
/gate/SPECThead/geometry/setZLength 18 cm
/gate/SPECThead/placement/setRotationAxis  1 0 0
/gate/SPECThead/placement/setRotationAngle -90 deg
/gate/SPECThead/vis/setColor white
/gate/SPECThead/setMaterial Air
/gate/SPECThead/vis/forceWireframe

# Shielding: main volume
/gate/SPECThead/daughters/name shielding
/gate/SPECThead/daughters/insert box
/gate/shielding/geometry/setXLength 57.6 cm
/gate/shielding/geometry/setYLength 44.6 cm
/gate/shielding/geometry/setZLength 11.1375 cm
/gate/shielding/placement/setTranslation 0. 0. -3.64 cm
/gate/shielding/setMaterial Steel
/gate/shielding/vis/setColor red
/gate/shielding/vis/forceWireframe


# Shielding: first layer of the lead cover
/gate/shielding/daughters/name shielding_lead_cover
/gate/shielding/daughters/insert box
/gate/shielding_lead_cover/geometry/setXLength 57.6 cm
/gate/shielding_lead_cover/geometry/setYLength 40.6 cm
/gate/shielding_lead_cover/geometry/setZLength  10.1375 cm
/gate/shielding_lead_cover/placement/setTranslation 0. 0. 0.5 cm
/gate/shielding_lead_cover/setMaterial Lead
/gate/shielding_lead_cover/vis/forceWireframe


# Shielding: Aluminium Cover
/gate/shielding_lead_cover/daughters/name shielding_aluminium_cover
/gate/shielding_lead_cover/daughters/insert box
/gate/shielding_aluminium_cover/geometry/setXLength 54. cm
/gate/shielding_aluminium_cover/geometry/setYLength 40. cm
/gate/shielding_aluminium_cover/geometry/setZLength 0.13 cm
/gate/shielding_aluminium_cover/placement/setTranslation 0. 0. 5.00375 cm
/gate/shielding_aluminium_cover/setMaterial Aluminium
/gate/shielding_aluminium_cover/vis/setColor blue
/gate/shielding_aluminium_cover/vis/forceWireframe


# Shielding: reflector TiO2
/gate/shielding_lead_cover/daughters/name shielding_reflector
/gate/shielding_lead_cover/daughters/insert box
/gate/shielding_reflector/geometry/setXLength 54. cm
/gate/shielding_reflector/geometry/setYLength 40. cm
/gate/shielding_reflector/geometry/setZLength  0.12 cm
/gate/shielding_reflector/placement/setTranslation 0. 0. 3.29125 cm
/gate/shielding_reflector/setMaterial TiO2
/gate/shielding_reflector/vis/setColor blue
/gate/shielding_reflector/vis/forceWireframe


# Shielding: crystal
/gate/shielding_lead_cover/daughters/name crystal_volume
/gate/shielding_lead_cover/daughters/insert box
/gate/crystal_volume/geometry/setXLength 54. cm
/gate/crystal_volume/geometry/setYLength 40. cm
/gate/crystal_volume/geometry/setZLength  1.5875 cm
/gate/crystal_volume/placement/setTranslation  0 0 4.145 cm
/gate/crystal_volume/setMaterial NaITl
/gate/crystal_volume/vis/setColor yellow
# special command to say that this volume is the crystal
/gate/systems/SPECThead/crystal/attach crystal_volume
# This is needed !
/gate/crystal_volume/attachCrystalSD


# Shielding: Backside
# The back-side is fairly complex, and may have a strong influence on the
# spectrum: the model shown here is simplified
/gate/shielding_lead_cover/daughters/name shielding_backside
/gate/shielding_lead_cover/daughters/insert box
/gate/shielding_backside/geometry/setXLength 54. cm
/gate/shielding_backside/geometry/setYLength 40. cm
/gate/shielding_backside/geometry/setZLength  8. cm
/gate/shielding_backside/placement/setTranslation 0. 0. -0.76875 cm
/gate/shielding_backside/setMaterial Pyrex66
